repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/joosthart/pre-commit-hook-mypy
    rev: v0.1.1
    hooks:
    -   id: mypy-committed
        # You can customize mypy behavior with args
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        # Add any additional dependencies your project needs
        additional_dependencies: ["types-requests", "django-stubs"] 