name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pre-commit
    - name: Run tests
      run: |
        ./test.sh
    - name: Test as pre-commit hook
      run: |
        mkdir -p test_repo && cd test_repo
        git init
        git config --local user.email "hartjoost@gmail.com"
        git config --local user.name "Joost Hart"
        cat > .pre-commit-config.yaml << EOF
        repos:
        -   repo: $(pwd)/..
            rev: main
            hooks:
            -   id: mypy-committed
        EOF
        pre-commit install
        cp ../test_example/good_file.py good.py
        git add good.py .pre-commit-config.yaml
        git commit -m "Add good file"  # This should pass
        cp ../test_example/bad_file.py bad.py
        git add bad.py
        ! git commit -m "Add bad file"  # This should fail 